version: '2'
services:
  casperjs:
   image: mar664/casperjs-container
   expose:
    - "5000"
   volumes:
    - /home/casperjs-cluster:/casperjs
   entrypoint:
    - nohup python server.py &
   restart: always
  lb:
    image: dockercloud/haproxy
    links:
      - casperjs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - EXTRA_FRONTEND_SETTINGS_80=acl allowed_page path_beg /render,acl allowed_page path_beg /capture,acl allowed_page path_beg /execute,block if !allowed_page
      - BALANCE=url_param session_id
    ports:
      - 8585:80