#cloud-config
package_upgrade: true
packages:
  - python-pip
  - git
runcmd:
  - cd /home
  - git clone https://github.com/mar664/casperjs-cluster.git
  - cd casperjs-cluster
  - pip install docker-compose
  - docker-compose up -d
  - docker-compose scale casperjs=5